name: Scrape YallaShoot (today.json)

on:
  schedule:
    - cron: "*/5 * * * *"   # كل 5 دقايق (UTC)
  workflow_dispatch:
    inputs:
      force_url:
        description: "اختياري: URL مخصص بدل الافتراضي"
        required: false

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Playwright + requests)
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          FORCE_URL: ${{ github.event.inputs.force_url }}
          # تقدر تغيّر مصدر LiveOnSat إذا صار خطأ
          LOS_URL: https://liveonsat.com/2day.php
        run: |
          python scripts/scrape_yallashoot_to_json.py

      - name: Show output
        run: |
          echo "---- matches/today.json ----"
          cat matches/today.json || true

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update matches/today.json (scraped)"
          file_pattern: matches/today.json
