name: Scrape (YallaShoot + LiveOnSat) → today.json

on:
  schedule:
    - cron: "*/5 * * * *"   # كل 5 دقائق (UTC)
  workflow_dispatch:
    inputs:
      force_url:
        description: "اختياري: URL مخصص ليلا شوت"
        required: false

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 pyyaml requests
          playwright install --with-deps chromium

      # 1) YallaShoot → matches/today.json
      - name: Scrape YallaShoot
        env:
          FORCE_URL: ${{ github.event.inputs.force_url }}
        run: |
          python scripts/scrape_yallashoot_to_json.py

      # 2) LiveOnSat → matches/liveonsat_raw.json
      - name: Scrape LiveOnSat
        run: |
          python scripts/scrape_liveonsat_only.py

      # 3) Merge → update matches/today.json (adds channels)
      - name: Merge channels into today.json
        run: |
          python scripts/merge_liveonsat_into_yallashoot.py
          echo "---- matches/today.json (after merge) ----"
          cat matches/today.json || true

      # اسحب آخر التغييرات قبل الدفع لتفادي non-fast-forward
      - name: Pull latest (rebase) to avoid non-fast-forward
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase --autostash origin "$(git rev-parse --abbrev-ref HEAD)" || true

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update matches/today.json (merged LiveOnSat channels)"
          file_pattern: |
            matches/today.json
            matches/liveonsat_raw.json
