# ุงุณู ุงููุฑู ููู ุงููู ุฑุงุญ ูุธูุฑ ูู ุตูุญุฉ Actions
name: Scrape and Filter Match Data

# ูุชู ูุดุชุบู ูุฐุง ุงููุฑู ูููุ
on:
  # 1. ุชุดุบูู ุฃูุชููุงุชููู ูุฌุฏูู (ููุง ูู 6 ุณุงุนุงุช)
  schedule:
    - cron: '0 */6 * * *'

  # 2. ุชุดุบูู ูุฏูู (ุชูุฏุฑ ุชุดุบูู ุจููุณู ูู ุตูุญุฉ Actions)
  workflow_dispatch:

  # 3. ุชุดุบูู ุนูุฏ ูู push ุนูู ุจุฑุงูุด ุงูู main (ูููุฏ ููุชุฌุฑุจุฉ)
  push:
    branches:
      - main

jobs:
  # ุงุณู ุงููููุฉ (Job)
  build-and-commit:
    # ุณูุชู ุชุดุบููู ุนูู ุณูุฑูุฑ ุฃูุจููุชู ุงูุชุฑุงุถู
    runs-on: ubuntu-latest

    steps:
      # ุงูุฎุทูุฉ 1: ูุณุฎ ููุฏ ุงููุดุฑูุน ููุณูุฑูุฑ ุงูุงูุชุฑุงุถู
      - name: Check out repository
        uses: actions/checkout@v4

      # ุงูุฎุทูุฉ 2: ุชูุตูุจ ุจุงูุซูู
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ุงูุฎุทูุฉ 3: ุชุซุจูุช ุงูููุชุจุงุช ุงููู ูุญุชุงุฌูุง ุงูุณูุฑุจุช
      - name: Install dependencies
        run: |
          pip install beautifulsoup4 playwright

      # ุงูุฎุทูุฉ 4: ุฎุทูุฉ ูููุฉ ุฌุฏุงู - ุชุซุจูุช ูุชุตูุญุงุช playwright
      - name: Install Playwright browsers
        run: playwright install --with-deps

      # ุงูุฎุทูุฉ 5: ุชุดุบูู ุณูุฑุจุช ุณุญุจ ุงูุจูุงูุงุช
      - name: Run Scraper
        run: python scripts/scrape_liveonsat_only.py

      # ุงูุฎุทูุฉ 6: ุชุดุบูู ุณูุฑุจุช ุงูููุชุฑุฉ
      - name: Run Filter
        run: python scripts/filter_json.py

      # ุงูุฎุทูุฉ 7: ุญูุธ ุงููุชุงุฆุฌ (ูููุงุช ุงูุฌูุณูู) ูู ุงูุฑูุจู ูุงูุชู
      - name: Commit and push JSON results
        run: |
          # ุชุนุฑูู ูุนูููุงุช ุงูุดุฎุต ุงููู ุณูู ุงูุชุบููุฑ (ุจูุช)
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # ุฅุถุงูุฉ ุงููููุงุช ุงูุฌุฏูุฏุฉ ุฃู ุงููู ุชุบูุฑุช ูููุฑุญูุฉ ุงููุงุฏูุฉ
          git add matches/liveonsat_raw.json matches/filtered_matches.json
          
          # ุงูุชุญูู ุฅุฐุง ูุงู ููุงู ุชุบููุฑุงุช ูุนููุฉ ูุจู ุงูููููุช
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
          else
            # ุนูู ููููุช ุจุงูุชุบููุฑุงุช ูุน ุฑุณุงูุฉ ุชุญุชูู ุนูู ุงูุชุงุฑูุฎ ูุงูููุช
            git commit -m "๐ Automated match data update"
            
            # ุฏูุน (push) ุงูููููุช ููุฑูุจู ูุงูุชู
            git push
          fi
