name: 1. Scrape Raw Match Data

on:
  schedule:
    - cron: '0 */12 * * *' # يعمل كل 12 ساعة
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium
      - name: Run Scraper
        run: python scripts/scrape_liveonsat_only.py
      - name: Commit & push raw data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: " Chomper: Update raw match data"
          file_pattern: "matches/liveonsat_raw.json"
