name: YallaShoot Daily JSON

on:
  schedule:
    # 11:00 UTC ≈ 14:00 بغداد (عدّل إذا تحب)
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-yallashoot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps + Python libs
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install-deps
          python -m playwright install chromium

      - name: Run scraper
        # إذا تحب تغيّر الرابط (نسخة ثانية من الصفحة) استخدم secret:
        # env:
        #   FORCE_URL: ${{ secrets.YS_URL }}
        run: |
          python scripts/scrape_yallashoot_to_json.py

      - name: Commit & push JSON
        run: |
          git config --global user.name "gh-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add matches/today.json
          git commit -m "update today.json [skip ci]" || echo "no changes"
          git push
